<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="robots" content="noindex,nofollow">
	<meta name="generator" content="Bludit">

	<title><?php echo $layout['title'] ?></title>
	<link rel="icon" type="image/x-icon" href="<?php echo HTML_PATH_CORE_IMG.'favicon.png?version='.BLUDIT_VERSION ?>">

	<?php
		echo Theme::cssBootstrap();
		echo Theme::css(array(
			'bludit-bootstrap.css',
			'easymde.min.css',
			'editor.css',
			'bludit.css'
		), DOMAIN_ADMIN_THEME_CSS);
	?>

	<?php Theme::plugins('adminHead') ?>
</head>
<body>

<?php Theme::plugins('adminBodyBegin') ?>

<!-- Javascript -->
<?php
	echo Theme::jquery();
	echo Theme::jsBootstrap();
	echo Theme::js(array(
		'easymde.min.js',
		'ajax.js',
		'parser.js',
		'page.js'
	), DOMAIN_ADMIN_THEME_JS);
?>

<!-- Javascript dynamic generated by PHP -->
<?php
	echo '<script charset="utf-8">'.PHP_EOL;
	include(PATH_CORE_JS.'variables.php');
	echo '</script>'.PHP_EOL;
?>

<?php
	activatePlugin('pluginAPI');
	$apiURL = DOMAIN_BASE.'api/';
	$pluginAPI = getPlugin('pluginAPI');
	$apiToken = $pluginAPI->getToken();
	$admin = new User($login->username());
	$authToken = $admin->tokenAuth();
?>

<script>
	/*
		Global variables
		all variables start with _ are global
	*/
	var _apiURL 	= "<?php echo $apiURL ?>";
	var _apiToken 	= "<?php echo $apiToken ?>";
	var _authToken 	= "<?php echo $authToken ?>";
	var _domainBase = "<?php echo DOMAIN_BASE ?>";

	// Current page loaded
	var _page = new Page();
</script>

<?php include('html/settings.php'); ?>

<div class="container-fluid h-100">
	<!-- 25%/75% split on large devices, small, medium devices hide -->
	<div class="row h-100 d-flex">
		<!-- LEFT SIDEBAR - Display only on large devices -->
		<?php include('html/sidebar.php'); ?>

		<!-- RIGHT MAIN -->
		<div class="editor-container col-lg-6 p-3">
		<?php include('html/main.php'); ?>
		</div>
	</div>
</div>

<?php Theme::plugins('adminBodyEnd') ?>

</body>
</html>